// AUTO-GENERATED by codegen.py — do not edit by hand.
// Source: smogon/pokemon-showdown data/pokedex.ts + data/moves.ts
// Re-run codegen.py to update.

use crate::data::types::Type;

pub static SPECIES: &[SpeciesData] = &[
    // [0] Dummy Sentinel
    SpeciesData { hp:  0, atk:  0, def:  0, spa:  0, spd:  0, spe:  0, type1:Type::Normal, type2:Type::Normal, weight:0 },
];

pub static FORMES: &[SpeciesData] = &[
];

/// Maps a Showdown forme key (e.g. "rotom-heat") to an index into FORMES.
/// Build this once at startup: `HashMap::from(FORME_INDEX_MAP)`.
pub static FORME_INDEX_MAP: &[(&str, usize)] = &[
];
