// AUTO-GENERATED by codegen.py — do not edit by hand.
// Source: smogon/pokemon-showdown data/pokedex.ts + data/moves.ts
// Re-run codegen.py to update.

use crate::data::types::Type;
use crate::data::moves::{MoveCategory, MoveTarget, VarPower};

/* Move Flags Bitmask Definition:
 * 0x0001 = CONTACT
 * 0x0002 = SOUND
 * 0x0004 = PUNCH
 * 0x0008 = PULSE
 * 0x0010 = BITE
 * 0x0020 = POWDER
 * 0x0040 = DANCE
 * 0x0080 = WIND
 * 0x0100 = SLICING
 * 0x0200 = PROTECT
 * 0x0400 = REFLECTABLE
 * 0x0800 = RECHARGE
 * 0x1000 = CHARGE
 * 0x2000 = HEAL
 * 0x4000 = BYPASSSUB
 */

pub static MOVES: &[MoveData] = &[
    // [0] Dummy Sentinel
    MoveData { base_power: 0, accuracy: 0, pp: 0, priority: 0, category: MoveCategory::Status, move_type: Type::Normal, target: MoveTarget::Normal, flags: 0x0000, var_power: VarPower::None, crit_ratio: 0, drain: 0, heal: 0, multihit_lo: 1, multihit_hi: 1, secondary_chance: 0, secondary_stat: 0 },
];
